### ISSUE TITLE
How to delete fake news?

### ISSUE THREAD

**Issue by jejer** [AtlasNX/PegaScape#2]
Hi,

How can I remove fake news after successfully setup emunand?
We should only need fake news in stock sysnand.

Thanks

**Comment by Jabooon** [comment]
Same here, I executed it by error and now I cant get rid of it in NEWs

**Comment by hax4dazy** [comment]
The fake news applet changes some system files i think to make this work. You will only get the original news back if you had made a backup before that and used that to create emunand.

**Comment by noahc3** [comment]
I can add an uninstall option to fakenews installer, gimme a bit

**Comment by noahc3** [comment]
Done, fake news injector now has an option to remove fake news: https://github.com/noahc3/fakenews-injector/releases/tag/v1.1.0
